version: '2'

services:
  app:
    image: 'java-application'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: 'springio/gs-spring-boot-docker1'
    container_name: db

