insert into owner(name, job)  values('Harrison', 'Engineer')
insert into owner(name, job) values('Charlie', 'Engineer')
insert into owner(name, job) values('Joshua', 'Engineer')
insert into tickets(id, description, finished)  values(1, 'Create a react front end', false)
insert into tickets(id, description, finished)  values(1, 'Create a mySQL backend', false)
insert into tickets(id, description, finished)  values(2, 'Test Thoroughly', false)
insert into tickets(id, description, finished)  values(3, 'Write backend', false)
insert into tickets(id, description, finished) values(1, 'Create a springboot project', false)
